### ISSUE TITLE
Is it me or you cannot remove apps?

### ISSUE THREAD

**Issue by FuriousBird** [UpsilonNumworks/Upsilon-External#15]
I've tried to add a file to read with the "reader" app but it makes me crash whenever i try to open it, sadly your app can only import, not remove file... Is it possible to add a list for currently installed apps and files where one can remove them?

**Comment by Lauryy06** [comment]
Can you send me the commit of your version ? Go in settings, about and click one time on the first row.

**Comment by FuriousBird** [comment]
okay thanks, i'll see what i can do i guess
