### ISSUE TITLE
Make "Install" button dynamic and change texts for better convenience

### ISSUE THREAD

**Issue by Rathmox** [UpsilonNumworks/Upsilon-External#28]
Replace "Install" with "remove all external content" when nothing is added and "Erase and Install" when you install something to explain that installing something will erase everything and install over it

**Comment by quentinguidee** [comment]
That being said, the install button will also erase all external content; I think this should also be noted somewhere with this solution.

**Comment by Rathmox** [comment]
> That being said, the install button will also erase all external content; I think this should also be noted somewhere with this solution.

"Erase and install"
This is why I added this, because you can't install without erasing what you installed before

**Comment by Yaya-Cout** [comment]
Done in 2e515b8078ab35712a1563f045570b1d8bb58cbf.
