### ISSUE TITLE
Basic "Hello World" template app

### ISSUE THREAD

**Issue by matteoturini** [UpsilonNumworks/Upsilon-External#6]
This would be useful to start development of external apps easily. Making a new repository with everything set up would be wonderful.

**Comment by UnlimitedKaos** [comment]
I would also like this, I would like to work on a project, but I'm unsure how/where to start.

**Comment by Yaya-Cout** [comment]
I think you can start with the Chip-8 emulator's code, it is very simple !

**Comment by Yaya-Cout** [comment]
I think I will do it.

**Comment by Oreig403** [comment]
There is already a template app on the omega repository that includes external and internal app

**Comment by Yaya-Cout** [comment]
Yes, but the external directory is empty.

**Comment by Oreig403** [comment]
Ah ok good luck

**Comment by Yaya-Cout** [comment]
What do you think of [this](https://github.com/Yaya-Cout/Upsilon-External/blob/example/apps/Example/main.c) ?

**Comment by UnlimitedKaos** [comment]
> What do you think of [this](https://github.com/Yaya-Cout/Upsilon-External/blob/example/apps/Example/main.c) ?

Thank you, This seems pretty straightforward to me.

This might be too unrelated, but is it possible to upload the external apps zip to the emulator instead of the calculator? I would think that if I crashed out my program it would probably freeze the calculator and Id have reset & reinstall firmware. It seem easier to me if I could build the emulator, and make a copy for each project im working on.

**Comment by Yaya-Cout** [comment]
I started to add the support of external files on the simulator, but external apps is more complicated, because there are built for the calculator's processor, not the computer's one…

**Comment by UnlimitedKaos** [comment]
Ah, I misunderstood what that was, I thought there was a full blown emulator.

**Comment by Yaya-Cout** [comment]
It is possible to build an external app into the simulator, but the screen refresh doesn't work…

**Comment by matteoturini** [comment]
Sorry for the long delay, how do I flash the app with a CLI?

**Comment by Lauryy06** [comment]
It's done in #10

**Comment by matteoturini** [comment]
Many thanks!
